export const fakeData = [
  {
    id: '1237gffdsf897j12kjg',
    localiztion: 'New York',
    dateTaken: new Date(),
    title: 'ddd',
    authorfirstName: 'Mateusz',
    authorlastName: 'Wojcieszak',
  },
  {
    id: '1237gffdsf897j12kjg',
    localiztion: 'New York',
    dateTaken: new Date(),
    title: 'ddd',
    authorfirstName: 'Mateusz',
    authorlastName: 'Wojcieszak',
  },
  {
    id: '1237gffdsf897j12kjg',
    localiztion: 'New York',
    dateTaken: new Date(),
    title: 'ddd',
    authorfirstName: 'Mateusz',
    authorlastName: 'Wojcieszak',
  },
  {
    id: '1237gffdsf897j12kjg',
    localiztion: 'New York',
    dateTaken: new Date(),
    title: 'ddd',
    authorfirstName: 'Mateusz',
    authorlastName: 'Wojcieszak',
  },
  {
    id: '1237gffdsf897j12kjg',
    localiztion: 'New York',
    dateTaken: new Date(),
    title: 'ddd',
    authorfirstName: 'Mateusz',
    authorlastName: 'Wojcieszak',
  },
  {
    id: '1237gffdsf897j12kjg',
    localiztion: 'New York',
    dateTaken: new Date(),
    title: 'ddd',
    authorfirstName: 'Mateusz',
    authorlastName: 'Wojcieszak',
  },
  {
    id: '1237gffdsf897j12kjg',
    localiztion: 'New York',
    dateTaken: new Date(),
    title: 'ddd',
    authorfirstName: 'Mateusz',
    authorlastName: 'Wojcieszak',
  },
  {
    id: '1237gffdsf897j12kjg',
    localiztion: 'New York',
    dateTaken: new Date(),
    title: 'ddd',
    authorfirstName: 'Mateusz',
    authorlastName: 'Wojcieszak',
  },
  {
    id: '1237gffdsf897j12kjg',
    localiztion: 'New York',
    dateTaken: new Date(),
    title: 'ddd',
    authorfirstName: 'Mateusz',
    authorlastName: 'Wojcieszak',
  },
  {
    id: '1237gffdsf897j12kjg',
    localiztion: 'New York',
    dateTaken: new Date(),
    title: 'ddd',
    authorfirstName: 'Mateusz',
    authorlastName: 'Wojcieszak',
  },
  {
    id: '1237gffdsf897j12kjg',
    localiztion: 'New York',
    dateTaken: new Date(),
    title: 'ddd',
    authorfirstName: 'Mateusz',
    authorlastName: 'Wojcieszak',
  },
  {
    id: '1237gffdsf897j12kjg',
    localiztion: 'New York',
    dateTaken: new Date(),
    title: 'ddd',
    authorfirstName: 'Mateusz',
    authorlastName: 'Wojcieszak',
  },
  {
    id: '1237gffdsf897j12kjg',
    localiztion: 'New York',
    dateTaken: new Date(),
    title: 'ddd',
    authorfirstName: 'Mateusz',
    authorlastName: 'Wojcieszak',
  },
  {
    id: '1237gffdsf897j12kjg',
    localiztion: 'New York',
    dateTaken: new Date(),
    title: 'ddd',
    authorfirstName: 'Mateusz',
    authorlastName: 'Wojcieszak',
  },
  {
    id: '1237gffdsf897j12kjg',
    localiztion: 'New York',
    dateTaken: new Date(),
    title: 'ddd',
    authorfirstName: 'Mateusz',
    authorlastName: 'Wojcieszak',
  },
  {
    id: '1237gffdsf897j12kjg',
    localiztion: 'New York',
    dateTaken: new Date(),
    title: 'ddd',
    authorfirstName: 'Mateusz',
    authorlastName: 'Wojcieszak',
  },
  {
    id: '1237gffdsf897j12kjg',
    localiztion: 'New York',
    dateTaken: new Date(),
    title: 'ddd',
    authorfirstName: 'Mateusz',
    authorlastName: 'Wojcieszak',
  },
  {
    id: '1237gffdsf897j12kjg',
    localiztion: 'New York',
    dateTaken: new Date(),
    title: 'ddd',
    authorfirstName: 'Mateusz',
    authorlastName: 'Wojcieszak',
  },
  {
    id: '1237gffdsf897j12kjg',
    localiztion: 'New York',
    dateTaken: new Date(),
    title: 'ddd',
    authorfirstName: 'Mateusz',
    authorlastName: 'Wojcieszak',
  },
  {
    id: '1237gffdsf897j12kjg',
    localiztion: 'New York',
    dateTaken: new Date(),
    title: 'ddd',
    authorfirstName: 'Mateusz',
    authorlastName: 'Wojcieszak',
  },
  {
    id: '1237gffdsf897j12kjg',
    localiztion: 'New York',
    dateTaken: new Date(),
    title: 'ddd',
    authorfirstName: 'Mateusz',
    authorlastName: 'Wojcieszak',
  },
  {
    id: '1237gffdsf897j12kjg',
    localiztion: 'New York',
    dateTaken: new Date(),
    title: 'ddd',
    authorfirstName: 'Mateusz',
    authorlastName: 'Wojcieszak',
  },
  {
    id: '1237gffdsf897j12kjg',
    localiztion: 'New York',
    dateTaken: new Date(),
    title: 'ddd',
    authorfirstName: 'Mateusz',
    authorlastName: 'Wojcieszak',
  },
  {
    id: '1237gffdsf897j12kjg',
    localiztion: 'New York',
    dateTaken: new Date(),
    title: 'ddd',
    authorfirstName: 'Mateusz',
    authorlastName: 'Wojcieszak',
  },
  {
    id: '1237gffdsf897j12kjg',
    localiztion: 'New York',
    dateTaken: new Date(),
    title: 'ddd',
    authorfirstName: 'Mateusz',
    authorlastName: 'Wojcieszak',
  },
  {
    id: '1237gffdsf897j12kjg',
    localiztion: 'New York',
    dateTaken: new Date(),
    title: 'ddd',
    authorfirstName: 'Mateusz',
    authorlastName: 'Wojcieszak',
  },
  {
    id: '1237gffdsf897j12kjg',
    localiztion: 'New York',
    dateTaken: new Date(),
    title: 'ddd',
    authorfirstName: 'Mateusz',
    authorlastName: 'Wojcieszak',
  },
];
